# Generated by Django 3.2.7 on 2021-12-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
